main:
  push:
    - docker:
        image: node:24
      volumes:
        - node_modules:copy-on-write
      stages:
        - name: install
          script: npm install
        - name: build
          script: npm run build

$:
  tag_push:
    - docker:
        image: node:24
      env:
        GH_TOKEN: ${GH_TOKEN}
        CNB_TOKEN: ${CNB_TOKEN}
      volumes:
        - node_modules:copy-on-write
      stages:
        - name: install
          script: npm install
        - name: build
          script: npm run build
        - name: sync-to-cnb-release
          script: node scripts/sync-to-cnb.mjs